
class CardName:
	BAKERY = "Bakery"
	FARM = "Farm"
	WHEAT_FIELD = "Wheat Field"
	CAFE = "Cafe"
	MINI_MARKET = "Mini Market"
	FOREST = "Forest"
	MINE = "Mine"
	MILK_FACTORY = "Milk Factory"
	FURNITURE_FACTORY = "Furniture Factory"
	FAMILY_RESTAURANT = "Family Restaurant"
	MALL = "Mall"
	PLANTATION = "Plantation"
	STADIUM = "Stadium"
	TELEVISION_TOWER = "Television Tower"
	OFFICE_BUILDING = "Office Building"
	TRAIN_STATION = "Train Station"
	SHOPPING_MALL = "Shopping Mall"
	AMUSEMENT_PARK = "Amusement Park"
	RADIO_TOWER = "Radio Tower"
